create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  lang text not null default 'hu',
  status text not null default 'new',
  source text not null default 'contact_form',
  admin_note text,
  created_at timestamptz not null default now()
);

create table if not exists public.portfolio_items (
  id bigint generated by default as identity primary key,
  path text not null unique,
  category text not null,
  title text not null,
  note text not null,
  lang text not null default 'hu',
  sort_order int not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.touch_portfolio_items_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_portfolio_items_updated_at on public.portfolio_items;
create trigger trg_portfolio_items_updated_at
before update on public.portfolio_items
for each row execute function public.touch_portfolio_items_updated_at();

insert into storage.buckets (id, name, public)
values ('portfolio-media', 'portfolio-media', false)
on conflict (id) do nothing;
