create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  lang text not null default 'hu',
  status text not null default 'new',
  source text not null default 'contact_form',
  admin_note text,
  created_at timestamptz not null default now()
);

create table if not exists public.portfolio_items (
  id bigint generated by default as identity primary key,
  path text not null unique,
  category text not null,
  title text not null,
  note text not null,
  lang text not null default 'hu',
  sort_order int not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gallery_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  image_path text not null,
  created_at timestamptz not null default now(),
  unique (user_id, image_path)
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  lang text not null default 'de',
  status text not null default 'pending',
  source text not null default 'homepage',
  consent boolean not null default false,
  confirmation_token text unique,
  confirmed_at timestamptz,
  resend_contact_id text,
  last_confirmation_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.newsletter_subscribers
  add column if not exists unsubscribe_token text unique;

alter table public.newsletter_subscribers
  add column if not exists unsubscribed_at timestamptz;

alter table public.newsletter_subscribers
  add column if not exists welcome_sent_at timestamptz;

alter table public.newsletter_subscribers
  add column if not exists followup_sent_at timestamptz;

create table if not exists public.newsletter_campaign_logs (
  id bigint generated by default as identity primary key,
  type text not null default 'campaign',
  lang text not null default 'de',
  subject text not null,
  heading text not null,
  intro text,
  body text,
  cta_text text,
  cta_url text,
  recipient_count int not null default 0,
  sent_count int not null default 0,
  failed_count int not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.newsletter_broadcast_jobs (
  id bigint generated by default as identity primary key,
  lang text not null default 'de',
  preset_key text,
  subject text not null,
  heading text not null,
  intro text,
  body text,
  cta_text text,
  cta_url text,
  scheduled_for timestamptz not null,
  status text not null default 'scheduled',
  recipient_count int not null default 0,
  sent_count int not null default 0,
  failed_count int not null default 0,
  error_message text,
  last_run_at timestamptz,
  processed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create or replace function public.touch_portfolio_items_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create or replace function public.touch_newsletter_subscribers_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_portfolio_items_updated_at on public.portfolio_items;
create trigger trg_portfolio_items_updated_at
before update on public.portfolio_items
for each row execute function public.touch_portfolio_items_updated_at();

drop trigger if exists trg_newsletter_subscribers_updated_at on public.newsletter_subscribers;
create trigger trg_newsletter_subscribers_updated_at
before update on public.newsletter_subscribers
for each row execute function public.touch_newsletter_subscribers_updated_at();

insert into storage.buckets (id, name, public)
values ('client-galleries', 'client-galleries', false)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('portfolio-media', 'portfolio-media', false)
on conflict (id) do nothing;
